### ISSUE TITLE
install issues and notes

### ISSUE THREAD

**Issue by kevinmarks** [snarfed/oauth-dropins#11]
I've had a series of annoyances getting this installed, so I thought I'd sum them up so we can edit documentation.
1. Virtualenv can't cope with spaces anywhere in the path, and fails annoyingly.
 After creating the virtualenv, but before activating it, edit the activate, easy_install and pip files in `[yourdir]/local/bin/` to escape any spaces in the path. eg in activate
`VIRTUAL_ENV="/Users/kevinmarks/my project/local"`
becomes
`VIRTUAL_ENV="/Users/kevinmarks/my\ project/local"`
and in pip and easy_install the first line changes from
`#!"/Users/kevinmarks/my project/local/bin/python"`
to
`#!"/Users/kevinmarks/my\ project/local/bin/python"`

This should get virtualenv to install in the right place. If you do this wrong first, you'll have installs in
`/usr/local/lib/python2.7/site-packages`
that you need to delete as virtualenv won't install into the local 'site-packages' if they are in there

2. importing requests will fail with a 
`ImportError: cannot import name certs`
error until you edit your app.yaml to include
```
libraries:
- name: ssl
  version: latest
```

3. tweepy fails unless six.py is installed (So I added it to project root)

4. tweepy gives a 400 error locally:

  File "/Users/kevinmarks/my project/local/lib/python2.7/site-packages/tweepy/auth.py", line 68, in _get_request_token
    raise TweepError(e)
TweepError: must be _socket.socket, not socket

**Comment by kevinmarks** [comment]
see http://bekt.github.io/p/gae-ssl/ for how to make the ssl stuff run socket locally

**Comment by snarfed** [comment]
thanks for filing! and yeah, i've been applying that local workaround every time my SDK gets upgraded. silly that they haven't put in a better official fix. all of this will be great to add to the docs!

**Comment by kevinmarks** [comment]
should six.py be in the dependency list?

**Comment by kylewm** [comment]
six is a [requirement for tweepy](https://pypi.python.org/pypi/tweepy/3.4.0), shouldn't it being pulled in transitively?
