### ISSUE TITLE
unittests fail to import testutil

### ISSUE THREAD

**Issue by kylewm** [snarfed/oauth-dropins#12]
Minor annoyance: `python -m unittest discover` thinks `oauth_dropins.webutil.testutil` is a test case because it is prefixed with "test", but when it tries to import, it gets 

```
  File "/home/kmahan/projects/oauth-dropins/oauth_dropins/webutil/testutil.py", line 10, in <module>
    import mox
ImportError: No module named mox
```

because `oauth_dropins.webutil.test.__init__` has not yet been imported to AppEngine-ify the sys.path. I don't really know a good way to fix this.

**Comment by snarfed** [comment]
huh, that's odd. `python -m unittest discover` in `oauth-dropins/` works fine for me.

i do have the app engine SDK on my `PYTHONPATH`, but i'm guessing you do too. when i remove it, i get an error in`test/__init__.py`, so it's still importing that first.

...ohhh interesting, i wonder if `discover` is nondeterministic somehow, so it happens to start with a different `test*` file for me, but is currently starting with `testutil` for you...?

(circle uses `python setup.py test` instead, so it's not helpful for debugging in this case: https://circleci.com/gh/snarfed/oauth-dropins)

**Comment by snarfed** [comment]
we're currently migrating to the new python 3 runtime, which drops pretty much all of the app engine quirks, so this issue will probably be obsolete.

**Comment by snarfed** [comment]
python 3 migration is done! tentatively closing.
